### ISSUE TITLE
More settings

### ISSUE THREAD

**Issue by kockok** [arpl/react-redux-boilerplate#2]
Hi, could you also add `vendor` or `CommonsChunkPlugin`?

BTW, you put all the dependencies into `devDependencies`, could this be intentional?

Thanks.

**Comment by arpl** [comment]
Since `webpack` is handling the build I don't see any strong reason to categorize npm dependencies. All node modules are necessary to produce a build. There are cases where the separation is useful and `npm install --production` makes sense.

Regarding `CommonsChunkPlugin`, it's already being used in production builds under `webpack.prod.js` which produces `common.bundle.js`.

Regard,
A

**Comment by kockok** [comment]
In [this](https://github.com/jagatjeevan/react-setup/blob/master/webpack.config.babel.js) config:

```
  entry: {
    main: path.resolve(__dirname, 'app/js/index.js'),
    vendor: [
      'react',
      'react-dom',
      'react-router'
    ]
  },
```
I can see that it specifies the `vendor` in entry whilst also use `CommonsChunkPlugin`.
So, should we also add `vendor` in the boilerplate?

**Comment by arpl** [comment]
I get your point now. After specifying actual library names I get more balanced asset sizes. 
Before
```
           Asset       Size  Chunks                    Chunk Names
       bundle.js     254 kB       0  [emitted]  [big]  bundle
common.bundle.js     202 kB       1  [emitted]         common
      bundle.css     135 kB       0  [emitted]         bundle
      index.html  508 bytes          [emitted]
```
After
```
           Asset       Size  Chunks                    Chunk Names
       bundle.js     453 kB       0  [emitted]  [big]  bundle
common.bundle.js    1.38 kB       1  [emitted]         common
      bundle.css     135 kB       0  [emitted]         bundle
      index.html  508 bytes          [emitted]
```
